version: '3.4'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    container_name: app
    restart: unless-stopped
    build:
      context: ./App
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`app.localhost`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.services.app.loadbalancer.server.port=3000
    depends_on:
      - graphql
  graphql:
    image: ${DOCKER_REGISTRY-}graphql
    container_name: graphql
    restart: unless-stopped
    build:
      context: ./GraphQL
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.graphql.rule=Host(`app.localhost`) && PathPrefix(`/graphql`)
      - traefik.http.routers.graphql.entrypoints=web
      - traefik.http.services.graphql.loadbalancer.server.port=80
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--ping=true"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - 80:80
      - 443:443
    

