version: '3.8'

services:
  app:
    image: app:dev
    build:
      context: ./App
      dockerfile: Dockerfile.dev
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    volumes:
      - "./App:/srv/app"
      - "app_node_modules:/srv/app/node_modules"
      - "app_next:/srv/app/.next"
  graphql:
    image: graphql:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  traefik:
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.middlewares=traefik-strip
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.rule=Host(`app.localhost`) && (PathPrefix(`/traefik`) || HeadersRegexp(`Referer`, `.*/traefik/.*`))
      - traefik.http.middlewares.traefik-strip.stripprefix.prefixes=/traefik

volumes:
  app_node_modules:
  app_next: