http:
  routers:
    app:
      entrypoints:
        - web
      service: app
      rule: PathPrefix(`/`)
      priority: 0
    graphql:
      service: graphql
      entrypoints:
        - web
      rule: PathPrefix(`/graphql`)
      priority: 100
    dashboard:
      entrypoints:
        - web
      middlewares:
        - traefik-strip
      service: api@internal
      rule: PathPrefix(`/traefik`) || HeadersRegexp(`Referer`, `.*/traefik/.*`)
      priority: 1000
  middlewares:
    traefik-strip:
      stripPrefix:
        prefixes:
          - /traefik
  services:
    app:
      loadBalancer:
        servers:
          - url: http://app:3000
    graphql:
      loadBalancer:
        servers:
          - url: http://graphql:80