overwrite: true
schema: http://localhost:8080/graphql?sdl=true
documents: 'src/**/*.graphql'
generates:
  src/graphql/myapp.ts:
    hooks:
        afterOneFileWrite:
          - eslint --fix
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query":
      - "fragment-matcher"
    config:
      fetcher:
        func: "@src/utils/useMyAppFetcher#useMyAppFetcher"
        isReactHook: true