overwrite: true
schema: myapp.graphql

#schema:
#  - "https://titan.localhost/graphql?sdl=true":
#      method: GET
#      headers:
#        Accept: application/graphql

generates:
  src/graphql/myapp.ts:
    documents:
      - "src/**/*.graphql"
    hooks:
        afterOneFileWrite:
          - eslint --fix
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query":
      - "fragment-matcher"
    config:
      fetcher:
        func: "@src/utils/useMyAppFetcher#useMyAppFetcher"
        isReactHook: true
          
        # endpoint: "'/graphql/'"
    extensions: 
      endpoints:
        default:
          url: "https://localhost:3001/graphql"