FROM node:14-alpine

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

ARG FONTAWESOME_NPM_AUTH_TOKEN
ENV FONTAWESOME_NPM_AUTH_TOKEN=${FONTAWESOME_NPM_AUTH_TOKEN}

WORKDIR /srv/app

RUN yarn global add pm2

COPY ./.npmrc ./
COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

VOLUME /srv/app

COPY docker-entrypoint-dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh
ENTRYPOINT ["docker-entrypoint-dev.sh"]
